### PR TITLE
Resolved invalid proof issue

### PR DESCRIPTION
**Pull request by DonleeIO**
The pairIndex for right nodes was out of range within the getProof() function, causing certain layers to be ignored. This was causing the getProof() function to return an invalid proof which only included left nodes. Therefore, the pairIndex value for right nodes should be equal to their index.

**This should close the following issue: #1**

### CODE REVIEW

**Comment by miguelmota** [comment]
@DonleeIO thanks for this PR, however most of the tests are failing now

**Comment by DonleeIO** [comment]
Thanks, I will look into it this evening. I plan to develop the unit test script further so that it’s more comprehensive. This may address the test failures.

**Comment by DonleeIO** [comment]
@miguelmota Thanks for highlighting this. The PR should only have applied to Bitcoin trees and the final item in the leaves object. My recent commits have addressed this and now all unit tests are passing.

**Comment by miguelmota** [comment]
Awesome! great work @DonleeIO

**Pull request merged**
